### ISSUE TITLE
Sphinx documentation for getting started, dataset, training, and prediction

### ISSUE THREAD

**Issue by jmduarte** [FAIR4HEP/hbb_interaction_network#12]
Add Sphinx documentation. Note the code lives in `docs` and it produces the following webpage: https://fair4hep.github.io/hbb_interaction_network/

This can be separate pages or adding doc strings to existing scripts I think (to be understood).

At a minimum, I would add a few pages:
- [ ] getting started: create a page with commands on how to process data, train, predict (with and/or without GPU?) inside of provided docker container @billy000400 
- [x] dataset: document the dataset features used; copying liberally from http://opendata.cern.ch/record/12102 @jmduarte
- [ ] training: document all options of training script @yorkiva 
- [ ] prediction: document all options of prediction script @poem2018 

Extras:
- [ ] explainable: document options of explainable AI script? @yorkiva

**Comment by yorkiva** [comment]
Hi @jmduarte, I have never used it so a little confused about how to get started. Some pointers would be useful and appreciated.

**Comment by jmduarte** [comment]
@yorkiva no problem.

Locally, you can `pip install sphinx` and other dependencies listed in `requirements.txt`. To build the documentation you can do the following:

```bash
cd docs
make html
```

Then just open `_build/html/index.html` in your web browser to see how the generated docs look.

You can make individual pages in restructured text (`.rst`) format (which is similar to markdown, but a bit different so look up the syntax). Then you can add it to the `index.rst` to make sure it gets listed on the generated home page.

You can also add doc strings to python function to automatically generate pages documenting those. I've added some examples to the branch. If you build it, it should look like this:
<img width="1552" alt="Screen Shot 2022-10-11 at 11 42 21 AM" src="https://user-images.githubusercontent.com/4932543/195150966-99fded84-67de-4898-9dcf-45cd8c73de96.png">


Here are some cheat sheets: 

- https://github.com/davidstutz/sphinx-example
- https://github.com/timstaley/sphinx-example
- https://eikonomega.medium.com/getting-started-with-sphinx-autodoc-part-1-2cebbbca5365

**Comment by yorkiva** [comment]
Hi @jmduarte, I added some documentation for the training script. After compiling, the part for training model looks like:

![image](https://user-images.githubusercontent.com/59802216/197407089-cccd1073-ff3e-4526-b5f2-9a4016110527.png)

Let me know if this works! I will accordingly edit the classes and methods for the xAI part
